/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountryCodeIndexRouteImport } from './routes/$countryCode/index'
import { Route as CountryCodeStoreRouteImport } from './routes/$countryCode/store'
import { Route as CountryCodeRegisterRouteImport } from './routes/$countryCode/register'
import { Route as CountryCodeLoginRouteImport } from './routes/$countryCode/login'
import { Route as CountryCodeCheckoutRouteImport } from './routes/$countryCode/checkout'
import { Route as CountryCodeCartRouteImport } from './routes/$countryCode/cart'
import { Route as CountryCodeAccountIndexRouteImport } from './routes/$countryCode/account/index'
import { Route as CountryCodeProductsHandleRouteImport } from './routes/$countryCode/products/$handle'
import { Route as CountryCodeCategoriesHandleRouteImport } from './routes/$countryCode/categories/$handle'
import { Route as CountryCodeAccountProfileRouteImport } from './routes/$countryCode/account/profile'
import { Route as CountryCodeAccountAddressesRouteImport } from './routes/$countryCode/account/addresses'
import { Route as CountryCodeAccountOrdersIndexRouteImport } from './routes/$countryCode/account/orders/index'
import { Route as CountryCodeOrderOrderIdConfirmedRouteImport } from './routes/$countryCode/order/$orderId/confirmed'
import { Route as CountryCodeAccountOrdersDetailsIdRouteImport } from './routes/$countryCode/account/orders/details/$id'
import { ServerRoute as HealthServerRouteImport } from './routes/health'

const rootServerRouteImport = createServerRootRoute()

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeIndexRoute = CountryCodeIndexRouteImport.update({
  id: '/$countryCode/',
  path: '/$countryCode/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeStoreRoute = CountryCodeStoreRouteImport.update({
  id: '/$countryCode/store',
  path: '/$countryCode/store',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeRegisterRoute = CountryCodeRegisterRouteImport.update({
  id: '/$countryCode/register',
  path: '/$countryCode/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeLoginRoute = CountryCodeLoginRouteImport.update({
  id: '/$countryCode/login',
  path: '/$countryCode/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeCheckoutRoute = CountryCodeCheckoutRouteImport.update({
  id: '/$countryCode/checkout',
  path: '/$countryCode/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeCartRoute = CountryCodeCartRouteImport.update({
  id: '/$countryCode/cart',
  path: '/$countryCode/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeAccountIndexRoute = CountryCodeAccountIndexRouteImport.update({
  id: '/$countryCode/account/',
  path: '/$countryCode/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeProductsHandleRoute =
  CountryCodeProductsHandleRouteImport.update({
    id: '/$countryCode/products/$handle',
    path: '/$countryCode/products/$handle',
    getParentRoute: () => rootRouteImport,
  } as any)
const CountryCodeCategoriesHandleRoute =
  CountryCodeCategoriesHandleRouteImport.update({
    id: '/$countryCode/categories/$handle',
    path: '/$countryCode/categories/$handle',
    getParentRoute: () => rootRouteImport,
  } as any)
const CountryCodeAccountProfileRoute =
  CountryCodeAccountProfileRouteImport.update({
    id: '/$countryCode/account/profile',
    path: '/$countryCode/account/profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const CountryCodeAccountAddressesRoute =
  CountryCodeAccountAddressesRouteImport.update({
    id: '/$countryCode/account/addresses',
    path: '/$countryCode/account/addresses',
    getParentRoute: () => rootRouteImport,
  } as any)
const CountryCodeAccountOrdersIndexRoute =
  CountryCodeAccountOrdersIndexRouteImport.update({
    id: '/$countryCode/account/orders/',
    path: '/$countryCode/account/orders/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CountryCodeOrderOrderIdConfirmedRoute =
  CountryCodeOrderOrderIdConfirmedRouteImport.update({
    id: '/$countryCode/order/$orderId/confirmed',
    path: '/$countryCode/order/$orderId/confirmed',
    getParentRoute: () => rootRouteImport,
  } as any)
const CountryCodeAccountOrdersDetailsIdRoute =
  CountryCodeAccountOrdersDetailsIdRouteImport.update({
    id: '/$countryCode/account/orders/details/$id',
    path: '/$countryCode/account/orders/details/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const HealthServerRoute = HealthServerRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/store': typeof StoreRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/login': typeof CountryCodeLoginRoute
  '/$countryCode/register': typeof CountryCodeRegisterRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode': typeof CountryCodeIndexRoute
  '/$countryCode/account/addresses': typeof CountryCodeAccountAddressesRoute
  '/$countryCode/account/profile': typeof CountryCodeAccountProfileRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/account': typeof CountryCodeAccountIndexRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
  '/$countryCode/account/orders': typeof CountryCodeAccountOrdersIndexRoute
  '/$countryCode/account/orders/details/$id': typeof CountryCodeAccountOrdersDetailsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/store': typeof StoreRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/login': typeof CountryCodeLoginRoute
  '/$countryCode/register': typeof CountryCodeRegisterRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode': typeof CountryCodeIndexRoute
  '/$countryCode/account/addresses': typeof CountryCodeAccountAddressesRoute
  '/$countryCode/account/profile': typeof CountryCodeAccountProfileRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/account': typeof CountryCodeAccountIndexRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
  '/$countryCode/account/orders': typeof CountryCodeAccountOrdersIndexRoute
  '/$countryCode/account/orders/details/$id': typeof CountryCodeAccountOrdersDetailsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/store': typeof StoreRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/login': typeof CountryCodeLoginRoute
  '/$countryCode/register': typeof CountryCodeRegisterRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/': typeof CountryCodeIndexRoute
  '/$countryCode/account/addresses': typeof CountryCodeAccountAddressesRoute
  '/$countryCode/account/profile': typeof CountryCodeAccountProfileRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/account/': typeof CountryCodeAccountIndexRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
  '/$countryCode/account/orders/': typeof CountryCodeAccountOrdersIndexRoute
  '/$countryCode/account/orders/details/$id': typeof CountryCodeAccountOrdersDetailsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/store'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/login'
    | '/$countryCode/register'
    | '/$countryCode/store'
    | '/$countryCode'
    | '/$countryCode/account/addresses'
    | '/$countryCode/account/profile'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/account'
    | '/$countryCode/order/$orderId/confirmed'
    | '/$countryCode/account/orders'
    | '/$countryCode/account/orders/details/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/store'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/login'
    | '/$countryCode/register'
    | '/$countryCode/store'
    | '/$countryCode'
    | '/$countryCode/account/addresses'
    | '/$countryCode/account/profile'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/account'
    | '/$countryCode/order/$orderId/confirmed'
    | '/$countryCode/account/orders'
    | '/$countryCode/account/orders/details/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/store'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/login'
    | '/$countryCode/register'
    | '/$countryCode/store'
    | '/$countryCode/'
    | '/$countryCode/account/addresses'
    | '/$countryCode/account/profile'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/account/'
    | '/$countryCode/order/$orderId/confirmed'
    | '/$countryCode/account/orders/'
    | '/$countryCode/account/orders/details/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  StoreRoute: typeof StoreRoute
  CountryCodeCartRoute: typeof CountryCodeCartRoute
  CountryCodeCheckoutRoute: typeof CountryCodeCheckoutRoute
  CountryCodeLoginRoute: typeof CountryCodeLoginRoute
  CountryCodeRegisterRoute: typeof CountryCodeRegisterRoute
  CountryCodeStoreRoute: typeof CountryCodeStoreRoute
  CountryCodeIndexRoute: typeof CountryCodeIndexRoute
  CountryCodeAccountAddressesRoute: typeof CountryCodeAccountAddressesRoute
  CountryCodeAccountProfileRoute: typeof CountryCodeAccountProfileRoute
  CountryCodeCategoriesHandleRoute: typeof CountryCodeCategoriesHandleRoute
  CountryCodeProductsHandleRoute: typeof CountryCodeProductsHandleRoute
  CountryCodeAccountIndexRoute: typeof CountryCodeAccountIndexRoute
  CountryCodeOrderOrderIdConfirmedRoute: typeof CountryCodeOrderOrderIdConfirmedRoute
  CountryCodeAccountOrdersIndexRoute: typeof CountryCodeAccountOrdersIndexRoute
  CountryCodeAccountOrdersDetailsIdRoute: typeof CountryCodeAccountOrdersDetailsIdRoute
}
export interface FileServerRoutesByFullPath {
  '/health': typeof HealthServerRoute
}
export interface FileServerRoutesByTo {
  '/health': typeof HealthServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/health': typeof HealthServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/health'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/health'
  id: '__root__' | '/health'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  HealthServerRoute: typeof HealthServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/': {
      id: '/$countryCode/'
      path: '/$countryCode'
      fullPath: '/$countryCode'
      preLoaderRoute: typeof CountryCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/store': {
      id: '/$countryCode/store'
      path: '/$countryCode/store'
      fullPath: '/$countryCode/store'
      preLoaderRoute: typeof CountryCodeStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/register': {
      id: '/$countryCode/register'
      path: '/$countryCode/register'
      fullPath: '/$countryCode/register'
      preLoaderRoute: typeof CountryCodeRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/login': {
      id: '/$countryCode/login'
      path: '/$countryCode/login'
      fullPath: '/$countryCode/login'
      preLoaderRoute: typeof CountryCodeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/checkout': {
      id: '/$countryCode/checkout'
      path: '/$countryCode/checkout'
      fullPath: '/$countryCode/checkout'
      preLoaderRoute: typeof CountryCodeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/cart': {
      id: '/$countryCode/cart'
      path: '/$countryCode/cart'
      fullPath: '/$countryCode/cart'
      preLoaderRoute: typeof CountryCodeCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/account/': {
      id: '/$countryCode/account/'
      path: '/$countryCode/account'
      fullPath: '/$countryCode/account'
      preLoaderRoute: typeof CountryCodeAccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/products/$handle': {
      id: '/$countryCode/products/$handle'
      path: '/$countryCode/products/$handle'
      fullPath: '/$countryCode/products/$handle'
      preLoaderRoute: typeof CountryCodeProductsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/categories/$handle': {
      id: '/$countryCode/categories/$handle'
      path: '/$countryCode/categories/$handle'
      fullPath: '/$countryCode/categories/$handle'
      preLoaderRoute: typeof CountryCodeCategoriesHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/account/profile': {
      id: '/$countryCode/account/profile'
      path: '/$countryCode/account/profile'
      fullPath: '/$countryCode/account/profile'
      preLoaderRoute: typeof CountryCodeAccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/account/addresses': {
      id: '/$countryCode/account/addresses'
      path: '/$countryCode/account/addresses'
      fullPath: '/$countryCode/account/addresses'
      preLoaderRoute: typeof CountryCodeAccountAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/account/orders/': {
      id: '/$countryCode/account/orders/'
      path: '/$countryCode/account/orders'
      fullPath: '/$countryCode/account/orders'
      preLoaderRoute: typeof CountryCodeAccountOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/order/$orderId/confirmed': {
      id: '/$countryCode/order/$orderId/confirmed'
      path: '/$countryCode/order/$orderId/confirmed'
      fullPath: '/$countryCode/order/$orderId/confirmed'
      preLoaderRoute: typeof CountryCodeOrderOrderIdConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/account/orders/details/$id': {
      id: '/$countryCode/account/orders/details/$id'
      path: '/$countryCode/account/orders/details/$id'
      fullPath: '/$countryCode/account/orders/details/$id'
      preLoaderRoute: typeof CountryCodeAccountOrdersDetailsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  StoreRoute: StoreRoute,
  CountryCodeCartRoute: CountryCodeCartRoute,
  CountryCodeCheckoutRoute: CountryCodeCheckoutRoute,
  CountryCodeLoginRoute: CountryCodeLoginRoute,
  CountryCodeRegisterRoute: CountryCodeRegisterRoute,
  CountryCodeStoreRoute: CountryCodeStoreRoute,
  CountryCodeIndexRoute: CountryCodeIndexRoute,
  CountryCodeAccountAddressesRoute: CountryCodeAccountAddressesRoute,
  CountryCodeAccountProfileRoute: CountryCodeAccountProfileRoute,
  CountryCodeCategoriesHandleRoute: CountryCodeCategoriesHandleRoute,
  CountryCodeProductsHandleRoute: CountryCodeProductsHandleRoute,
  CountryCodeAccountIndexRoute: CountryCodeAccountIndexRoute,
  CountryCodeOrderOrderIdConfirmedRoute: CountryCodeOrderOrderIdConfirmedRoute,
  CountryCodeAccountOrdersIndexRoute: CountryCodeAccountOrdersIndexRoute,
  CountryCodeAccountOrdersDetailsIdRoute:
    CountryCodeAccountOrdersDetailsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  HealthServerRoute: HealthServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
